language: objective-c
osx_image: xcode8
script: xcodebuild -project MDTestFramework/MDTestFramework.xcodeproj -scheme Release
#xcode_project: MDTestFramework/MDTestFramework.xcodeproj
#xcode_scheme: Release
#xcode_sdk: iphonesimulator
# safelist
branches:
  only:
  - Swift-3.0
